#Mapping of file extensions to languages
language_extensions = {
    '.java': 'Java',
    '.cpp': 'C++',
    '.go': 'Go',
    '.py': 'Python',
    '.js': 'JavaScript',
    '.c': 'C',
    '.rb': 'Ruby',
    '.php': 'PHP',
    '.ts': 'TypeScript',
    '.rs': 'Rust',
    '.html': 'HTML',
    '.css': 'CSS',
    '.json': 'JSON',
    '.pcap': 'PCAP',
    '.pcapng': 'PCAP Next-Gen',
    '.pdf': 'PDF',
    '.xlsx': 'MS Excel',
    '.docx': 'MS Word',
    '.pptx': 'MS PowerPoint',
    '.txt': 'Plain Text',
    '.png': 'PNG',
    '.jpg': 'JPG',
    '.jpeg': 'JPEG',
    '.md': 'Markdown',
    '.exe': 'Windows Executables',
    '.sh': 'Bash Scripts',
    '.bat': 'Batch Scripts',
    '.log': 'Log Files',
    '.conf': 'Linux Config Files',
    '.asm': 'Assembly',
    '.iso': 'ISO Files',
    '.vmdk': 'VMWare Virtual Disk Files',
    '.dll': 'Dynamic Link Libraries',
    '.sig': 'Signatures',
    '.dat': 'DAT',
    '.pak': 'Game Package Files',
    '.vdf': 'Valve Data Files',
    '.tga': 'Truevision TGA',
    '.bin': 'Generic Binaries',
    '.sys': 'System Files',
    '.cfg': 'Configuration Files',
    '.cmd': 'Windows Command Line',
    '.ps1': 'PowerShell Scripts',
    '.reg': 'Windows Registery Files',
    '.evtx': 'Windows Event Logs',
    '.csv': 'CSV',
    '.so': 'Shared Object Files',
    '.apk': 'Android Package Files',
    '.deb': 'Debian Package Files',
    '.rpm': 'Fedora Package Files',
    '.zip': 'ZIP Archives',
    '.rar': 'RAR Archives',
    '.7z': '7-Zip Archives',
    '.gz': 'Gzip Compressed Files',
    '.tar': 'TAR Archives',
    '.bz2': 'Bzip2 Compressed Files',
    '.db': 'Generic Database Files',
    '.sqlite': 'SQLite',
    '.plist': 'Property List (macOS)',
    '.pf': 'Windows prefetch files',
    '.hprof': 'Java Heap Dump Files',
    '.jar': 'Java Archive Files',
    '.msi': 'Windows Installers',
    '.vbs': 'Visual Basic Scripts',
    '.class': 'Compiled Java Classes',
    '.lnk': 'Windows Shortcut Files',
    '.hta': 'HTML Application Files',
    '.dmp': 'Memory Dump Files',
    '.har': 'HTTP Archive Files',
    '.crt': 'Certificate Files',
    '.key': 'Private Keys',
    '.enc': 'Encrypted Files',
    '.keychain': 'Keychain Files (macOS)',
}